name: Desplegar en Netlify

on:
  push:
    branches: [ main ]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar Netlify CLI
        run: npm install -g netlify-cli

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependencias y construir proyecto
        run: |
          pnpm install
          pnpm run build

      - name: Desplegar en Netlify
        run: npx netlify deploy --prod --dir=.next
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
